@startmindmap
'https://plantuml.com/mindmap-diagram



* 工时 79H
** Tool 52H
*** 收取邮件 24H
**** 功能按钮 8H
**** 展示列表 8H 
**** 条件查询表单 8H

*** 查询邮件 24H
**** 功能按钮 8H
**** 展示列表 8H 
**** 条件查询表单 8H

*** 身份角色菜单权限 4H
** ToolService 27H
*** 入库记录接口 7H
*** 邮箱简历接口 10H
**** 不索引字段处理 5H
**** 基本信息查询 5H
*** 渠道信息接口 6H
*** ESB调用封装 4H




@endmindmap
